"""
GuruDev IPII – IPIIEngine v0.1-beta
Generates minimal valid Python from canonical adapted blocks + detected intent.

Header:
  # Generated by GuruDev IPII v0.1-beta
  # Intent: calculo_numerico [ACAO][CIENCIA] herm=4

MAPEAMENTOS_BETA contains at least 15 curated mappings from GuruDev
function/resource names to Python equivalents.
"""
from __future__ import annotations

import textwrap

from gurudev.ipii.intent_analyzer import Intent

# ── Beta mappings ─────────────────────────────────────────────────────────────
# Each entry: gurudev_name -> {"import": <module>, "call": <python_expr_template>}
# {args} in "call" is replaced by the function parameter list.

MAPEAMENTOS_BETA: dict[str, dict[str, str]] = {
    # Math / calculus
    "fatorial": {"import": "math", "call": "math.factorial({args})"},
    "factorial": {"import": "math", "call": "math.factorial({args})"},
    "raiz": {"import": "math", "call": "math.sqrt({args})"},
    "sqrt": {"import": "math", "call": "math.sqrt({args})"},
    "potencia": {"import": "math", "call": "math.pow({args})"},
    "pow": {"import": "math", "call": "math.pow({args})"},
    "seno": {"import": "math", "call": "math.sin({args})"},
    "cosseno": {"import": "math", "call": "math.cos({args})"},
    "tangente": {"import": "math", "call": "math.tan({args})"},
    "log": {"import": "math", "call": "math.log({args})"},
    "logaritmo": {"import": "math", "call": "math.log({args})"},
    # Statistics / aggregations
    "media": {"import": "statistics", "call": "statistics.mean({args})"},
    "mediana": {"import": "statistics", "call": "statistics.median({args})"},
    "desvio_padrao": {"import": "statistics", "call": "statistics.stdev({args})"},
    "soma": {"import": "builtins", "call": "sum({args})"},
    "produto": {"import": "math", "call": "math.prod({args})"},
    # Science / physics helpers
    "formula_energia": {"import": "builtins", "call": "'{args}' # E = mc²"},
    "formula_euler": {"import": "cmath", "call": "cmath.exp(1j * cmath.pi) + 1"},
    # Generic fallback
    "calcular": {"import": "math", "call": "math.fabs({args})"},
}

_HEADER = "# Generated by GuruDev IPII v0.1-beta"

# ── Templates per intent ──────────────────────────────────────────────────────

_SIMPLE_FUNC_TEMPLATE = textwrap.dedent(
    '''\
    {header}
    # Intent: {intent_name} {tags} herm={herm}
    {import_line}

    def {func_name}({params}):
        """{docstring}"""
        return {body}
    '''
)

_DISPATCH_TEMPLATE = textwrap.dedent(
    '''\
    {header}
    # Intent: {intent_name} {tags} herm={herm}

    def {func_name}(recurso, hermeneutica: int = 1):
        """{docstring}"""
        dispatch = {{
    {cases}
        }}
        return dispatch.get(hermeneutica, dispatch.get("default", recurso))
    '''
)

_GENERIC_TEMPLATE = textwrap.dedent(
    '''\
    {header}
    # Intent: {intent_name} {tags} herm={herm}

    def transpiled():
        """{docstring}"""
        pass
    '''
)


# ── Engine ────────────────────────────────────────────────────────────────────


class IPIIEngine:
    """Generate Python source from adapted blocks and inferred intent."""

    def generate(self, adapted_blocks: list, intent: Intent) -> str:
        """Return a Python source string."""
        # Find the first FUNCTION block, if any
        func_block = self._find_function(adapted_blocks)
        dispatch_block = self._find_dispatch(adapted_blocks)

        if intent.name == "despacho_multiplo" and dispatch_block:
            return self._render_dispatch(dispatch_block, intent)

        if func_block:
            return self._render_function(func_block, intent)

        return self._render_generic(intent)

    # ── Finders ──────────────────────────────────────────────────────────────

    def _find_function(self, blocks: list) -> dict | None:
        for b in blocks:
            if b.get("kind") == "function":
                return b
        return None

    def _find_dispatch(self, blocks: list) -> dict | None:
        for b in blocks:
            if b.get("kind") == "dispatch":
                return b
        return None

    # ── Renderers ─────────────────────────────────────────────────────────────

    def _render_function(self, func: dict, intent: Intent) -> str:
        nome = func.get("nome", "transpiled")
        params = func.get("parametros", [])
        params_str = ", ".join(params) if params else "n"

        mapping = MAPEAMENTOS_BETA.get(nome.lower())
        if mapping:
            import_mod = mapping["import"]
            import_line = (
                f"import {import_mod}" if import_mod != "builtins" else ""
            ).strip()
            args = params_str
            body = mapping["call"].replace("{args}", args)
        else:
            import_line = "import math"
            body = f"# TODO: implement {nome}"

        return _SIMPLE_FUNC_TEMPLATE.format(
            header=_HEADER,
            intent_name=intent.name,
            tags=intent.tags,
            herm=intent.hermeneutics,
            import_line=import_line,
            func_name=nome,
            params=params_str,
            docstring=f"Transpiled from GuruDev: {intent.name}",
            body=body,
        )

    def _render_dispatch(self, dispatch: dict, intent: Intent) -> str:
        recurso = dispatch.get("recurso", "recurso")
        casos = dispatch.get("casos", {})
        default = dispatch.get("default")

        lines = []
        for nivel, body in casos.items():
            # Use integer keys for numeric levels (matching the hermeneutica: int param)
            try:
                key = int(nivel)
            except (ValueError, TypeError):
                key = nivel
            lines.append(f"        {repr(key)}: {repr(body)},")
        if default is not None:
            lines.append(f'        "default": {repr(default)},')

        cases_str = "\n".join(lines) if lines else '        1: recurso,'

        return _DISPATCH_TEMPLATE.format(
            header=_HEADER,
            intent_name=intent.name,
            tags=intent.tags,
            herm=intent.hermeneutics,
            func_name=f"despachar_{recurso}",
            docstring=f"Transpiled from GuruDev: {intent.name}",
            cases=cases_str,
        )

    def _render_generic(self, intent: Intent) -> str:
        return _GENERIC_TEMPLATE.format(
            header=_HEADER,
            intent_name=intent.name,
            tags=intent.tags,
            herm=intent.hermeneutics,
            docstring=f"Transpiled from GuruDev: {intent.name}",
        )
