"""
GuruDev IPII – IPIITranspiler v0.1
Transpila código GuruDev para Python executável.

Suporta:
  - Blocos imperativos: ASSIGN, IF, WHILE, FOR (controle de fluxo v0.2)
  - Blocos funcionais/dispatch: delega ao IPIIEngine existente
  - Níveis hermenêuticos 1–7: preserva comentários de nível e emite
    código de geração do DecisionTrace para níveis >= 4.
"""
from __future__ import annotations

import textwrap

from gurudev.ipii.bytecode_adapter_real import BytecodeAdapterReal
from gurudev.ipii.engine import IPIIEngine
from gurudev.ipii.intent_analyzer import IntentAnalyzer

_HEADER = "# Generated by GuruDev IPII v0.1-beta"

# ── Helpers ────────────────────────────────────────────────────────────────────

_DECISION_TRACE_IMPORT = textwrap.dedent(
    """
    from typing import Any, Optional
    import json as _json
    """
)

_DECISION_TRACE_HELPER = textwrap.dedent(
    """
    def _make_decision_trace(kind: str, level: int, condition: str,
                              condition_value: Optional[bool],
                              taken_branch: Optional[str],
                              iterations: Optional[int],
                              events: list) -> dict:
        graph = None
        if level >= 6:
            graph = {"nodes": [{"id": "condition", "type": "condition"}],
                     "edges": []}
        return {
            "kind": kind, "level": level, "condition": condition,
            "condition_value": condition_value, "taken_branch": taken_branch,
            "iterations": iterations,
            "events": events[:1] if level == 4 else events,
            "graph": graph,
        }
    """
)


# ── Transpiler ─────────────────────────────────────────────────────────────────


class IPIITranspiler:
    """
    Transpila código GuruDev (fonte ou bytecode) para Python executável.

    Uso:
        transpiler = IPIITranspiler()
        python_code = transpiler.transpile_source(codigo_guru, nivel=4)
    """

    def transpile_source(self, source: str, nivel: int = 4,
                          filename: str = "<input>") -> str:
        """Transpila código-fonte GuruDev para Python.

        Args:
            source: código GuruDev como string.
            nivel: nível hermenêutico alvo (1–7).
            filename: nome do arquivo (para mensagens de erro).

        Returns:
            String Python válida e executável.
        """
        from compiler.bytecode_gen import BytecodeGenerator
        from compiler.context_analyzer import ContextAnalyzer
        from compiler.lexer import Lexer
        from compiler.parser import Parser

        tokens = Lexer(source, filename).tokenizar()
        ast = Parser(tokens).parse()
        ContextAnalyzer().analisar(ast)
        gurubyte = BytecodeGenerator().gerar(ast)
        gurubyte["CONTEXT_DEFAULT"]["hermeneutics"] = nivel
        return self.transpile_bytecode(gurubyte, nivel)

    def transpile_bytecode(self, gurubyte: dict, nivel: int = 4) -> str:
        """Transpila um GuruByte dict para Python.

        Estratégia:
          - Se contém blocos imperativos (ASSIGN/IF/WHILE/FOR) → transpilação
            direta.
          - Caso contrário → delega ao IPIIEngine existente.
        """
        codeblocks = gurubyte.get("CODEBLOCKS", [])
        has_imperative = any(
            b.get("type") in ("ASSIGN", "IF", "WHILE", "FOR")
            for b in codeblocks
        )

        if has_imperative:
            return self._transpile_imperative(gurubyte, nivel)

        # Fallback: pipeline IPII clássico (FUNCTION / DISPATCH)
        adapter = BytecodeAdapterReal()
        intent_analyzer = IntentAnalyzer()
        engine = IPIIEngine()
        adapted = adapter.adapt(gurubyte)
        intent = intent_analyzer.analyze(adapted)
        intent.hermeneutics = nivel
        return engine.generate(adapted, intent)

    # ── Transpilação imperativa ────────────────────────────────────────────────

    def _transpile_imperative(self, gurubyte: dict, nivel: int) -> str:
        """Gera Python imperativo a partir dos CODEBLOCKS."""
        lines: list[str] = [
            _HEADER,
            f"# Hermeneutics level: {nivel}",
            "# Source: GuruDev v0.2 — controle de fluxo",
            "",
        ]

        needs_trace = nivel >= 4
        if needs_trace:
            lines.append(_DECISION_TRACE_IMPORT.strip())
            lines.append("")
            lines.append(_DECISION_TRACE_HELPER.strip())
            lines.append("")
            lines.append(f"_NIVEL = {nivel}")
            lines.append("_decision_traces: list[dict] = []")
            lines.append("")

        # Collect variable names used as display operands
        var_names = self._collect_var_names(gurubyte.get("CODEBLOCKS", []))

        for block in gurubyte.get("CODEBLOCKS", []):
            block_lines = self._transpile_block(block, 0, var_names, nivel, needs_trace)
            lines.extend(block_lines)

        return "\n".join(lines) + "\n"

    def _collect_var_names(self, blocks: list) -> set[str]:
        """Coleta nomes de variáveis atribuídas para distinguir de literais em display."""
        names: set[str] = set()
        for block in blocks:
            btype = block.get("type", "")
            if btype == "ASSIGN":
                names.add(block.get("var", ""))
            elif btype == "FOR":
                names.add(block.get("var", ""))
                names.update(self._collect_var_names(block.get("body", [])))
            elif btype in ("WHILE", "IF"):
                names.update(self._collect_var_names(block.get("body", [])))
                names.update(self._collect_var_names(block.get("then", [])))
                names.update(self._collect_var_names(block.get("else", [])))
        return names

    def _transpile_block(self, block: dict, indent: int,
                          var_names: set[str], nivel: int,
                          needs_trace: bool) -> list[str]:
        btype = block.get("type", "")
        pfx = "    " * indent
        lines: list[str] = []

        if btype == "ASSIGN":
            var = block.get("var", "_")
            expr = self._transpile_expr(block.get("expr", {}))
            lines.append(f"{pfx}{var} = {expr}")

        elif btype == "IF":
            cond = self._transpile_expr(block.get("condition", {}))
            cond_repr = repr(self._expr_repr(block.get("condition", {})))
            if needs_trace:
                lines.append(f"{pfx}_cond_val = bool({cond})")
                lines.append(f"{pfx}_taken = 'then' if _cond_val else 'else'")
                lines.append(f"{pfx}if _cond_val:")
            else:
                lines.append(f"{pfx}if {cond}:")

            then_lines = []
            for sub in block.get("then", []):
                then_lines.extend(
                    self._transpile_block(sub, indent + 1, var_names, nivel, needs_trace)
                )
            if then_lines:
                lines.extend(then_lines)
            else:
                lines.append(f"{pfx}    pass")

            if block.get("else"):
                lines.append(f"{pfx}else:")
                else_lines = []
                for sub in block.get("else", []):
                    else_lines.extend(
                        self._transpile_block(sub, indent + 1, var_names, nivel, needs_trace)
                    )
                if else_lines:
                    lines.extend(else_lines)
                else:
                    lines.append(f"{pfx}    pass")

            if needs_trace:
                lines.append(
                    f"{pfx}_decision_traces.append(_make_decision_trace("
                    f"'if', _NIVEL, {cond_repr}, _cond_val, _taken, None, "
                    f"[{{'event': 'branch', 'condition_value': _cond_val, 'taken': _taken}}]))"
                )

        elif btype == "WHILE":
            cond = self._transpile_expr(block.get("condition", {}))
            cond_repr = repr(self._expr_repr(block.get("condition", {})))
            if needs_trace:
                lines.append(f"{pfx}_iter_count = 0")
                lines.append(f"{pfx}_events: list = []")
                lines.append(f"{pfx}while {cond}:")
                body_pfx = "    " * (indent + 1)
                lines.append(f"{body_pfx}_events.append({{'event': 'iteration', 'iteration': _iter_count}})")
            else:
                lines.append(f"{pfx}while {cond}:")

            body_lines: list[str] = []
            for sub in block.get("body", []):
                body_lines.extend(
                    self._transpile_block(sub, indent + 1, var_names, nivel, needs_trace)
                )
            if body_lines:
                lines.extend(body_lines)
            else:
                lines.append(f"{'    ' * (indent + 1)}pass")

            if needs_trace:
                lines.append(f"{'    ' * (indent + 1)}_iter_count += 1")
                lines.append(
                    f"{pfx}_decision_traces.append(_make_decision_trace("
                    f"'while', _NIVEL, {cond_repr}, None, None, _iter_count, _events))"
                )

        elif btype == "FOR":
            var = block.get("var", "i")
            iterable = self._transpile_expr(block.get("iterable", {}))
            iter_repr = repr(self._expr_repr(block.get("iterable", {})))
            if needs_trace:
                lines.append(f"{pfx}_iter_count = 0")
                lines.append(f"{pfx}_events = []")
                lines.append(f"{pfx}for {var} in {iterable}:")
                body_pfx = "    " * (indent + 1)
                lines.append(
                    f"{body_pfx}_events.append({{'event': 'iteration', 'iteration': _iter_count, '{var}': {var}}})"
                )
            else:
                lines.append(f"{pfx}for {var} in {iterable}:")

            for_body: list[str] = []
            for sub in block.get("body", []):
                for_body.extend(
                    self._transpile_block(sub, indent + 1, var_names, nivel, needs_trace)
                )
            if for_body:
                lines.extend(for_body)
            else:
                lines.append(f"{'    ' * (indent + 1)}pass")

            if needs_trace:
                lines.append(f"{'    ' * (indent + 1)}_iter_count += 1")
                lines.append(
                    f"{pfx}_decision_traces.append(_make_decision_trace("
                    f"'for', _NIVEL, {iter_repr}, None, None, _iter_count, _events))"
                )

        elif btype in ("FUNCTION", ""):
            # Instruction block or function — delegate to a simplified renderer
            for instr in block.get("instructions", []):
                instr_line = self._transpile_instruction(instr, pfx, var_names)
                if instr_line:
                    lines.append(instr_line)

        return lines

    def _transpile_instruction(self, instr: dict, pfx: str, var_names: set[str]) -> str:
        opcode = instr.get("opcode", "")
        operandos = instr.get("operandos", [])
        if opcode == "DISPLAY":
            if instr.get("modificadores", {}).get("in_context"):
                return f"{pfx}print('(display in context)')"
            if operandos:
                raw = operandos[0]
                if raw in var_names:
                    return f"{pfx}print({raw})"
                return f"{pfx}print({repr(raw)})"
            return f"{pfx}print()"
        elif opcode == "LOAD":
            name = operandos[0] if operandos else "?"
            return f"{pfx}# LOAD {name}"
        elif opcode == "EVALUATE":
            name = operandos[0] if operandos else "?"
            return f"{pfx}# EVALUATE {name}"
        return ""

    # ── Expressões ─────────────────────────────────────────────────────────────

    def _transpile_expr(self, expr: dict) -> str:
        """Converte expressão serializada em código Python."""
        kind = expr.get("kind", "")
        if kind == "literal":
            val = expr.get("value")
            return repr(val)
        if kind == "var":
            return expr.get("name", "_unknown")
        if kind == "binop":
            left = self._transpile_expr(expr.get("left", {}))
            right = self._transpile_expr(expr.get("right", {}))
            op = expr.get("op", "?")
            return f"({left} {op} {right})"
        if kind == "call":
            func = expr.get("func", "_")
            args = ", ".join(self._transpile_expr(a) for a in expr.get("args", []))
            return f"{func}({args})"
        return "None"

    def _expr_repr(self, expr: dict) -> str:
        """Representação textual de uma expressão (para comentários/traces)."""
        kind = expr.get("kind", "")
        if kind == "literal":   return str(expr.get("value"))
        if kind == "var":       return expr.get("name", "?")
        if kind == "binop":
            return (f"{self._expr_repr(expr.get('left', {}))} "
                    f"{expr.get('op')} "
                    f"{self._expr_repr(expr.get('right', {}))}")
        if kind == "call":
            args = ", ".join(self._expr_repr(a) for a in expr.get("args", []))
            return f"{expr.get('func')}({args})"
        return "?"
